# Generated by Django 6.0.5 on 2026-05-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='description',
        ),
    ]
