# Generated by Django 6.0.5 on 2026-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_companyinfo_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Сотрудник должен быть старше 18 лет', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Формат: +375 (XX) XXX-XX-XX', max_length=20, verbose_name='Телефон'),
        ),
    ]
