# Generated by Django 6.0.5 on 2026-05-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_birth_date_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='phone',
            field=models.CharField(help_text='Формат: +375 (XX) XXX-XX-XX', max_length=20, verbose_name='Телефон'),
        ),
    ]
