# Generated by Django 6.0.5 on 2026-05-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('conditions', models.TextField(verbose_name='Условия работы')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Заработная плата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_date'],
            },
        ),
    ]
