# Generated by Django 6.0.5 on 2026-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_producttype_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0), ('purchase_price__isnull', True), _connector='OR'), name='purchase_price_non_negative'),
        ),
    ]
