# Generated by Django 6.0.5 on 2026-05-12 07:51

import products.models.suppliers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_saleitem_quantity_alter_supply_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Покупатель должен быть старше 18 лет', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Формат: +375 (XX) XXX-XX-XX', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(help_text='+375 (XX) XXX-XX-XX', max_length=20, validators=[products.models.suppliers.validate_phone], verbose_name='Телефон'),
        ),
    ]
