# Generated by Django 6.0.5 on 2026-05-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_customer_birth_date_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
