# Generated by Django 6.0.5 on 2026-05-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discounted_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма после применения промокода', max_digits=12, verbose_name='Итоговая стоимость со скидкой'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена товара на момент продажи', max_digits=10, verbose_name='Цена за единицу'),
            preserve_default=False,
        ),
    ]
