# Generated by Django 6.0.5 on 2026-05-12 10:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sale_discounted_total_amount_saleitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена товара на момент продажи', max_digits=10, verbose_name='Цена за единицу'),
        ),
    ]
